### ISSUE TITLE
Error executing action `install` on resource 'git_client[default]'

### ISSUE THREAD

**Issue by martinb3** [jssjr/git#56]
We started receiving reports yesterday that the new git cookbook release from @someara does not work with some versions of the community MySQL cookbook, such as https://github.com/rackspace-cookbooks/platformstack/issues/198. The reports all come with a similar stack trace:

```
Recipe: git::default
  * git_client[default] action install
 
    ================================================================================
    Error executing action `install` on resource 'git_client[default]'
    ================================================================================
 
    NoMethodError
    -------------
    undefined method `package_version' for Chef::Resource::AptPackage
 
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/mysql/libraries/resource_mysql_service.rb:59:in `parsed_package_version'
    /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb:16:in `block (2 levels) in <class:Package>'
    /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb:14:in `block in <class:Package>'
 
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/git/recipes/default.rb
 
     19: git_client 'default' do
     20:   action :install
     21: end
 
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/git/recipes/default.rb:19:in `from_file'
 
    git_client("default") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :git_client
      cookbook_name "git"
      recipe_name "default"
    end
```

I can't figure out how `git/libraries/provider_git_client_package.rb:16` is calling a method from `mysql/libraries/resource_mysql_service.rb` -- I don't see any require statements that would even expose these to each other, but there you have it. Maybe some Chef magic due to the LWRP classes being included/extended?

**Comment by martinb3** [comment]
I just found -- https://github.com/chef-cookbooks/mysql/commit/93d6467670a98fefc4471a2f082cd236c085eefa. I think that's where it was fixed. I'll move this over to that repo, and hope we could get a 5.x release of mysql to fix it. Thanks!
