### ISSUE TITLE
undefined method `windows_package_version' for Chef::Resource::GitClient

### ISSUE THREAD

**Issue by puneetloya** [jssjr/git#73]
Installing git client on windows using the recipe has the above error. I am installing it via test-kitchen and chef

**Comment by smurawski** [comment]
Looks like this broke somewhere in the 4.2.x line.  Version 4.0.2 works currently.  I'll dig in further in the next few days. /cc @someara

**Comment by docwhat** [comment]
Full error output with version 4.3.1 running on Chef 12.3.0:

## NoMethodError

`undefined method `windows_package_version' for Chef::Resource::GitClient`

### Resource Declaration:

```
# In C:/chef/cache/cookbooks/git/recipes/package.rb

 32:   git_client 'default' do
 33:     action :install
 34:   end
 35: end
```

### Compiled Resource:

```
# Declared in C:/chef/cache/cookbooks/git/recipes/package.rb:32:in `from_file'

git_client("default") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :git_client
  cookbook_name "git"
  recipe_name "package"
end
```

### Stacktrace

```
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:959:in `method_missing'
C:/chef/cache/cookbooks/git/libraries/helpers.rb:34:in `parsed_windows_package_version'
C:/chef/cache/cookbooks/git/libraries/helpers.rb:30:in `parsed_windows_display_name'
C:/chef/cache/cookbooks/git/libraries/provider_git_client_windows.rb:10:in `block in <class:Windows>'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:63:in `load'
C:/opscode/chef/bin/chef-client:63:in `<main>'
```

**Comment by docwhat** [comment]
It looks like the git client resource doesn't have a method called `windows_package_version`.

**Comment by docwhat** [comment]
4.2.2 is the last working version on Linux and Windows due to this bug and bug #72.

**Comment by smurawski** [comment]
@docwhat yep, it's missing an attribute/property in the resource for windows_package_version.  I've got an incoming PR to fix it (and get the spec tests working for Windows)

**Comment by docwhat** [comment]
@smurawski Yay! 🍻
